# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c5e50f447e9f94e7f9dda32060b5a07dc926ca12bb967461707e7e17e4aa65a03abf17ef5c58d949c532b93cc6497cce7bf58a1e69ad458fe19ff30d23d1e60b

test:
  secret_key_base: e4fac9d797ecf31ad94f8241499ae4025e74513dd4d0306351845630ce598d4c23057f80a7c8e64878c50a9a168f6d27812f5fcce0f7e637f569e3326e12d671

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
