# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 08b6784c8e5a99421c2a87780bc69dfc63e1c46d2613257769f6ee4fff89d8965c25fc76c3528cb97c63103a44a3889467168a441ddda35bc3ae2106e1b1430e

test:
  secret_key_base: edb38a66be7e866eb5ae0e7287783373d376fb7080235dd3ffacaf72ca6f85e3aae37ee61f53eefb91992dd07b67e3629e75e8ab32ed5de17015d5265ef3526f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
