# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9ab24a20022d9f1493ff5503899dcbb154742893e0cd55f6b73f404640129fad04bcf903889ede51871bd4e3d9ad3f595cb2c4aa376ac123b5bb430e563be310

test:
  secret_key_base: a22273e1536924d4d8a8de33db1524925ab4fd7712f8c8d684840ed685f9c82a033f37737afed19abeaae499fe088802e41b4aaac616044f246dbe67f698eb02

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
