# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8feb92f63d601fc2258a4ca2594e0f1c4fdebf2e65cb0f9f5c67e65e3bbe9ed47febf19f49c28c81a2f37fcd45ebb3205f30aa86175b0596aa975d39ece25af1

test:
  secret_key_base: d6be5bb1b5be6c40bbcc1b18a944dc7b5d2ca85d65f2d2435084a5a792b615599b1e66b8705a06309e538e3c768219e39887138f4dbbaff772179e35b050b696

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
